    zn "%SYS"

    do ##class(Security.Users).UnExpireUserPasswords("*")

    do $SYSTEM.OBJ.Load("/home/irisowner/dev/App.Installer.cls", "ck")
    set sc = ##class(App.Installer).setup()

    zn "IRISAPP"

    do $SYSTEM.OBJ.Load("/home/irisowner/dev/src/life/LifeModern.mac", "ck")
    do $SYSTEM.OBJ.Load("/home/irisowner/dev/src/life/LifeClassic.mac", "ck")
    do $SYSTEM.OBJ.Load("/home/irisowner/dev/src/web/LifeWeb.cls", "ck")

    halt
